---
- name: Include OS-Specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yaml'
        - '{{ansible_os_family}}.yaml'
        - default.yaml
      paths:
        - 'vars'

- name: Ensure that the package cache is updated
  ansible.builtin.package:
  args: "{{ ansible_builtin_package }}"
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- include_tasks: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- name: Ensure that the essential packages are installed
  ansible.builtin.package:
    name:
      - "ca-certificates"
      - "htop"
      - "unzip"
    state: present
