---
- name: Ensure that the package cache is updated
  ansible.builtin.package:
    update_cache: true
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- include_tasks: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- name: Ensure that the required packages are installed
  ansible.builtin.package:
    name:
      - "ca-certificates"
      - "htop"
      - "unzip"
    state: present
